CREATE DATABASE retaildata

USE retaildata

SELECT * FROM customer
SELECT * FROM prod_cat_info
SELECT * FROM transactions


--DATA PREPARATION AND UNDERSTANDING

--1.What is the total number of rows in each of the 3 tables in the database?

SELECT 'customer' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM customer UNION

SELECT 'prod_cat_info' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM prod_cat_info UNION

SELECT 'transations' AS TABLE_NAME, COUNT(*) AS NO_OF_RECORDS FROM transactions; 

--2.What is the total number of transactions that have a return?

SELECT COUNT(transaction_id) [return] 
FROM transactions
WHERE qty<0 and total_amt<0;

--3.As you would have noticed, the dates provided across the datasets are not in a correct format as first steps, pls convert the date variables into valid date formats before proceeding ahead.
--4.What is the time range of the transaction data available for analysis? 
--Show the output in number of days, months and years simultaneously in different columns.

SELECT DATEDIFF( DAY,MIN(tran_date),MAX(tran_date)) [day],DATEDIFF(MONTH,MIN(tran_date),MAX(tran_date)) [month],DATEDIFF(YEAR,MIN(tran_date),MAX(tran_date)) [year]
FROM transactions;

--5.Which product category does the sub-category “DIY” belong to?

SELECT prod_cat,prod_subcat 
FROM prod_cat_info 
WHERE prod_subcat in ('diy');

--DATA ANALYSIS

--1.Which channel is most frequently used for transactions?

SELECT store_type,COUNT(transaction_id) [count] 
FROM transactions
GROUP BY store_type ORDER BY COUNT(transaction_id) DESC;

--2.What is the count of Male and Female customers in the database?

SELECT gender,COUNT(gender) [count] 
FROM customer 
WHERE gender is not null GROUP BY gender;

--3.From which city do we have the maximum number of customers and how many?

SELECT TOP 5 city_code ,COUNT(customer_id) [count]
FROM Customer
GROUP BY city_code ORDER BY COUNT(customer_id) DESC;

--4..How many sub-categories are there under the Books category?

SELECT prod_cat,COUNT(prod_subcat) [count] 
FROM prod_cat_info 
WHERE prod_cat in ('books') GROUP BY prod_cat;

--5.What is the maximum quantity of products ever ordered?

SELECT prod_cat_code,prod_subcat_code,MAX(qty) [max quantity] 
FROM Transactions 
GROUP BY prod_cat_code,prod_subcat_code;

--6.What is the net total revenue generated in categories Electronics and Books?

SELECT t1.prod_cat, SUM(total_amt) [net tot revenue] 
FROM Transactions t2 join prod_cat_info t1 ON t2.prod_cat_code = t1.prod_cat_code  GROUP BY t1.prod_cat 
HAVING prod_cat in ('electronics','books');

--7.How many customers have >10 transactions with us, excluding returns?

SELECT cust_id,COUNT(cust_id) [count]
FROM Transactions
WHERE qty>0 GROUP BY cust_id 
HAVING (COUNT(transaction_id)>10); 
 
--8.What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT SUM(total_amt) [total revenue]
FROM Transactions t2   join prod_cat_info t1 ON t2.prod_cat_code=t1.prod_cat_code
WHERE Store_type='flagship' and prod_cat in ('electronics','clothing');

--9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT t1.prod_subcat,SUM(total_amt)-SUM(tax) revenue,t3.gender
FROM Transactions t2 join Customer t3 ON t2.cust_id=t3.customer_Id join prod_cat_info t1 ON t2.prod_subcat_code=t1.prod_sub_cat_code 
WHERE prod_cat='electronics' and Gender='m' GROUP BY gender,prod_subcat;

--10..What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

SELECT t1.prod_subcat,SUM(qty)/
(SELECT SUM(qty)*100 FROM Transactions WHERE Qty<0) [% of return],SUM(total_amt)/
(SELECT SUM(total_amt) FROM Transactions)*100 [%ofsales] 
FROM Transactions t2 join prod_cat_info t1 ON t2.prod_cat_code=t1.prod_cat_code and
t1.prod_sub_cat_code=t2.prod_subcat_code
GROUP BY prod_subcat ORDER BY sum(total_amt) DESC; 

--11.For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

SELECT SUM(total_amt) [Net revenue]
FROM Customer t1 join Transactions t2 ON t1.customer_id = t2.cust_id
WHERE DATEDIFF(YEAR,DOB,GETDATE()) between 25 and 35 and tran_date= (DATEADD(DAY,-30,(SELECT MAX(tran_date)[max date] 
FROM Transactions)));

--12.Which product category has seen the max value of returns in the last 3 months of transaction?

SELECT TOP 1 t1.prod_cat,t2.Qty 
FROM prod_cat_info t1 join Transactions t2 ON t1.prod_cat_code=t2.prod_cat_code
WHERE tran_date between DATEADD(MONTH,-3,(SELECT MAX(tran_date) FROM Transactions)) and 
(SELECT MAX(tran_date) FROM Transactions) and Qty<0
GROUP BY t1.prod_cat,t2.Qty ORDER BY t1.prod_cat;

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?

SELECT t1.store_type ,SUM(total_amt) [max amount], SUM(qty) [max qty] 
FROM Transactions t1 
GROUP BY Store_type ORDER BY [max amount] DESC,[max qty]DESC;

--14.What are the categories for which average revenue is above the overall average.

SELECT t1.prod_cat , AVG(total_amt) [Avg revenue]
FROM prod_cat_info t1 join Transactions t2 ON t1.prod_cat_code = t2.prod_cat_code
GROUP BY t1.prod_cat 
HAVING AVG(total_amt)>(SELECT AVG(total_amt) FROM Transactions);

--15.Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT t1.prod_subcat,AVG(total_amt) [avg revenue],SUM(total_amt) [tot revenue]
FROM prod_cat_info t1 join Transactions t2 ON t1.prod_cat_code =t2.prod_cat_code 
WHERE prod_cat in (SELECT TOP 5 prod_cat FROM Transactions join prod_cat_info ON Transactions.prod_cat_code=prod_cat_info.prod_cat_code GROUP BY prod_cat ORDER BY SUM(qty)DESC) 
GROUP BY t1.prod_subcat ORDER BY t1.prod_subcat;
 